apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: musicconnect
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: us-east-1
        url: https://k8s-us-east-1.musicconnect.com
      - cluster: us-west-2
        url: https://k8s-us-west-2.musicconnect.com
      - cluster: eu-west-1
        url: https://k8s-eu-west-1.musicconnect.com
      - cluster: ap-southeast-1
        url: https://k8s-ap-southeast-1.musicconnect.com
  template:
    metadata:
      name: '{{cluster}}-musicconnect'
    spec:
      project: default
      source:
        repoURL: https://github.com/musicconnect/infrastructure
        targetRevision: HEAD
        path: kubernetes/overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: musicconnect
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - Validate=true
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: musicconnect
  namespace: argocd
spec:
  description: MusicConnect production project
  sourceRepos:
  - 'https://github.com/musicconnect/*'
  destinations:
  - namespace: 'musicconnect*'
    server: '*'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  - group: 'policy'
    kind: PodDisruptionBudget
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: admin
    policies:
    - p, proj:musicconnect:admin, applications, *, musicconnect/*, allow
    - p, proj:musicconnect:admin, repositories, *, *, allow
    groups:
    - musicconnect:admins
  - name: readonly
    policies:
    - p, proj:musicconnect:readonly, applications, get, musicconnect/*, allow
    groups:
    - musicconnect:developers