apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: musicconnect-backend-hpa
  namespace: musicconnect
  labels:
    app: musicconnect-backend
    app.kubernetes.io/name: musicconnect-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: musicconnect
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: musicconnect-backend
  minReplicas: 3
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "1k"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 5
        periodSeconds: 30
      selectPolicy: Max
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: musicconnect-frontend-hpa
  namespace: musicconnect
  labels:
    app: musicconnect-frontend
    app.kubernetes.io/name: musicconnect-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: musicconnect
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: musicconnect-frontend
  minReplicas: 3
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 3
        periodSeconds: 30
      selectPolicy: Max
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: musicconnect-websocket-hpa
  namespace: musicconnect
  labels:
    app: musicconnect-websocket
    app.kubernetes.io/name: musicconnect-websocket
    app.kubernetes.io/component: websocket
    app.kubernetes.io/part-of: musicconnect
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: musicconnect-websocket
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: websocket_connections
      target:
        type: AverageValue
        averageValue: "1000"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 120
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max