# This is a template file. DO NOT commit actual secrets to version control.
# Use a secrets management tool like AWS Secrets Manager, HashiCorp Vault, or sealed-secrets.
apiVersion: v1
kind: Secret
metadata:
  name: musicconnect-database
  namespace: musicconnect
  labels:
    app: musicconnect
    app.kubernetes.io/name: musicconnect-database
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: musicconnect
type: Opaque
stringData:
  url: "postgresql://username:password@hostname:5432/musicconnect"
---
apiVersion: v1
kind: Secret
metadata:
  name: musicconnect-redis
  namespace: musicconnect
  labels:
    app: musicconnect
    app.kubernetes.io/name: musicconnect-redis
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: musicconnect
type: Opaque
stringData:
  url: "redis://username:password@hostname:6379"
  auth-token: "your-redis-auth-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: musicconnect-jwt
  namespace: musicconnect
  labels:
    app: musicconnect
    app.kubernetes.io/name: musicconnect-jwt
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: musicconnect
type: Opaque
stringData:
  secret: "your-jwt-secret-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: musicconnect-stripe
  namespace: musicconnect
  labels:
    app: musicconnect
    app.kubernetes.io/name: musicconnect-stripe
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: musicconnect
type: Opaque
stringData:
  secret-key: "sk_live_your-stripe-secret-key"
  webhook-secret: "whsec_your-webhook-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: musicconnect-aws
  namespace: musicconnect
  labels:
    app: musicconnect
    app.kubernetes.io/name: musicconnect-aws
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: musicconnect
type: Opaque
stringData:
  access-key-id: "your-aws-access-key-id"
  secret-access-key: "your-aws-secret-access-key"