apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: musicconnect-backend-hpa
spec:
  minReplicas: 5
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: External
    external:
      metric:
        name: sqs_queue_length
        selector:
          matchLabels:
            queue_name: musicconnect-tasks-us-east-1
      target:
        type: AverageValue
        averageValue: "30"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: musicconnect-frontend-hpa
spec:
  minReplicas: 5
  maxReplicas: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: musicconnect-websocket-hpa
spec:
  minReplicas: 3
  maxReplicas: 30