apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: us-east-1-

commonLabels:
  region: us-east-1
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml

configMapGenerator:
  - name: region-config
    literals:
      - AWS_REGION=us-east-1
      - S3_BUCKET=musicconnect-us-east-1-media-production
      - CLOUDFRONT_DISTRIBUTION_ID=E1234567890ABC
      - REDIS_CLUSTER_NODES=redis-us-east-1-001.cache.amazonaws.com:6379,redis-us-east-1-002.cache.amazonaws.com:6379,redis-us-east-1-003.cache.amazonaws.com:6379

secretGenerator:
  - name: region-secrets
    literals:
      - DATABASE_URL=postgresql://musicconnect:password@aurora-us-east-1.cluster-abc123.us-east-1.rds.amazonaws.com:5432/musicconnect

replicas:
  - name: musicconnect-backend
    count: 5
  - name: musicconnect-frontend
    count: 5
  - name: musicconnect-websocket
    count: 3